# Generated by Django 4.2.2 on 2023-06-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_information',
            fields=[
                ('user_id', models.CharField(db_column='USER_ID', max_length=15, primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_column='USER_NAME', max_length=10)),
                ('user_password', models.CharField(db_column='USER_PASSWORD', max_length=25)),
            ],
        ),
    ]
